### ISSUE TITLE
USER STORY: Add profile picture on nav bar

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#10]
As a **user** I can **see and click my profile picture** so that **view which account I am logged in from and view/edit it when I want**
## Acceptance Criteria
* There should be a profile logo on the navbar.
* There should be a user name as well along with the profile picture.
* User can see his/her image when seeing the navbar.
* User can redirect to the profile when clicking the profile icon or name.
# Tasks
- [x] Create a profile image holder on the right of the navbar once logged in.
- [x] Right next to it add the profile holder's name
- [x] On clicking make sure the user is redirected to the profile page.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
