### ISSUE TITLE
USER STORY: Add feed and voted options on nav bar

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#11]
As a **user** I can **view the current feed and the votes I have given on the products** so that **observe the current situation of the products and my status of votes on products I have voted**
## Acceptance Criteria
* There should be a feed option on the navbar.
* There should be a voted option on the navbar.
* On clicking these options user should be redirected to relevant pages.
# Tasks
- [x] Create a feed option on the navbar.
- [x] Create a voted option on the navbar.
- [x] These options should be available once the user is logged in
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed
