### ISSUE TITLE
USER STORY: Upload Image

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#12]
As a **user** I can **upload an image in a post** so that **others can upvote/downvote by viewing it.**
## Acceptance Criteria
* There should be an area where it says Click or tap to upload an image.
* There should be an upload logo as well.
* Users should be redirected to Windows Explorer to select and upload an image of their choice.
* The image should have criteria for small size only.
* User can change the image again as needed.
# Tasks
- [x] Create an area where it is mentioned to tap or click.
- [x] Make sure the image size is small.
- [x] Create a method where the user can replace the image again.
- [x] The area designated should be responsive as per different screen sizes.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
