### ISSUE TITLE
USER STORY: Add Post title

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#13]
As a **user** I can **add title to a post** so that **others can read what the product actually is.**
## Acceptance Criteria
* There should be a text area that says title.
* There should be a word title mentioned above the text area pointing out that below is the text area.
* Users should not be restricted to 35 characters for the title.

# Tasks
- [x] Create a text that says the title.
- [x] Create a text area for the title.
- [x] Restrict user to only 35 words for title.
- [x] The title area designated should be responsive on different screen sizes.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
