### ISSUE TITLE
USER STORY: Content Area

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#14]
As a **user** I can **add content for a post** so that **others can read what the product is in detail.**
## Acceptance Criteria
* There should be a text area that says content.
* There should be a word content mentioned above the text area pointing out that below is the text area for it.
* Users should not be restricted to 500 characters for the content.

# Tasks
- [x] Create a text that says the content.
- [x] Create a text area for the content.
- [x] Restrict user to only 500 words for content.
- [x] The content area designated should be responsive on different screen sizes.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
