### ISSUE TITLE
USER STORY: Select Category that best defines the post

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#15]
As a **user** I can **select the category of the post that best defines it** so that **others can understand which category the product belongs to.**
## Acceptance Criteria
* There should be a drop-down which had a list of product categories.
* User can click one of the categories that best defines the post.
* User can select others if the category is not mentioned in the list.
# Tasks
- [x] Create a dropdown for the category of products.
- [x] Make sure the drop-down menu is clickable.
- [x] Add other as an additional category inside the list.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
