### ISSUE TITLE
USER STORY: Create or Cancel post creation

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#16]
As a **user** I can **create or cancel a creation of a post** so that **either share a new post with others or cancel the post if I change my mind about it**
## Acceptance Criteria
* There should be a button for creating a post.
* There should be a button for canceling a post.
* Before creating a post check if all the required fields are filled.
# Tasks
- [x] Create a button on the add post page for post creation.
- [x] Create a button on the add post page for post canceling.
- [x] Check all the required fields are filled before pressing the create button.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
