### ISSUE TITLE
USER STORY: Content of single Post Data

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#17]
As a **user** I can **view single post data** so that **I can view all the data related to it**
## Acceptance Criteria
* The user should be able to see I can view a single post.
* The post must contain the post image.
* The post must contain the logo of the user who posted it.
* Up and down vote option.
* Comments option.
* Post Title and Content and its Category.
* The user should also be able to see location and price.
# Tasks
- [x] Create a single post page.
- [x] Show the post data mentioned in the criteria.
- [x] The page should be responsive.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
