### ISSUE TITLE
USER STORY: Vote on products posts pages

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#18]
As a **user** I can **vote on posts** so that **I can vote for best or worst products**.
## Acceptance Criteria
* There should be a thumbs-up icon for upvoting a product post.
* There should be a thumbs-down icon for downvoting a product post.
* There should be a count of total thumbs up and down for each post.
* There should be an option to remove a vote.
* Post owner is not eligible to vote.
* Only logged-in users can vote.
# Tasks
- [x] Get thumbs-up, thumbs-down, and cross icons from font awesome.
- [x] Make sure the thumbs-up icon is on the left remove the vote in the middle and thumbs down on the right.
- [x] When clicking thumbs-up and down, they should change color showing which one is active.
- [x] Make sure that cross removes any active votes of current users on a post.
- [x] The total of both votes should be presented inside the table of a single post.
- [x] Test all the functions.

**Comment by MBilalQureshi** [comment]
The issue is now closed.
