### ISSUE TITLE
USER STORY: Home page posts Infinite scroll

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#20]
As a **user** I can **keep scrolling for new posts** so that **I can keep getting new information for myself without interruptions**
## Acceptance Criteria
* The posts must keep on loading on scrolling.
* Only new posts must appear instead of redundant ones.
# Tasks
- [x] Install infinite scroll 
- [x] Integrate infinite scroll with the home posts page.
- [x] Make sure new content keeps on appearing and scroll getting smaller.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
