### ISSUE TITLE
USER STORY: Search bar

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#21]
As a **user** I can **search posts based on price, location, date, title, content, and category** so that **I can find the posts I am looking for**.
## Acceptance Criteria
* There should be a search bar on top of the home page.
* The user could search for posts based on price, location, date, title, content, and category.
* The results should appear after a few seconds of typing so that the user can finish writing.
* The results should still follow the #17 criteria.
# Tasks
- [x] Create a search bar below the navbar.
- [x] It should be responsive as per screen size.
- [x] Create a method to generate posts based on search.
- [x] Create a loader that should appear before results.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
