### ISSUE TITLE
USER STORY: User posts on which he/she had voted on home page.

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#22]
As a **user** I can **click voted on the navbar on home page** so that **I can view the posts again on which I have voted on.**
## Acceptance Criteria
* There should be a voted button on the nav bar.
* It should be clickable.
* It should show data based on the filter applied to it.
* The search should still work on the data fetched based on the filter.
# Tasks
- [x] Create a filter for the posts on which the user had voted.
- [x] Show message of no data in case no vote on any post exists.
- [x] Show a message of no data in case no item is found after the search.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
