### ISSUE TITLE
USER STORY: Edit and delete post from drop down menu of each post

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#23]
As a **user** I can **update and delete posts by clicking on the top right corner of posts that belong to me** so that **I can modify posts as needed.**
## Acceptance Criteria
* There should be three dots on the top right corner of each post.
* The dots should be clickable.
* It should show a drop-down for editing or deleting posts.
* On clicking edit, the page should redirect to the edit post section.
* On clicking delete, the post should be deleted.
# Tasks
- [x] Create a drop-down on the top right corner of each post.
- [x] Provide this option to only the user the posts belong to.
- [x] Show icons to edit or delete which should be functional for their purposes.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
