### ISSUE TITLE
USER STORY: Edit posts

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#24]
As a **user** I can **edit my post** so that **I can update data of my posts**.
## Acceptance Criteria
* User can only update their own posts.
* The three-dot options should only be available for users' own posts.
* Once redirected to the edit page. Users are able to edit everything related to the post.
# Tasks
- [x] Create a method for editing posts.
- [x] Handle users only editing their own posts.
- [x] Make sure data is saved successfully once the edited post is submitted.
- [x] Handle all the fields appropriately before submitting.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
