### ISSUE TITLE
USER STORY: Comments section under posts

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#25]
As a **logged-in user** I can **add comments to a post** so that **I can share my thoughts about the post**
## Acceptance Criteria
* Under every post there should be a text area to add comments.
* User can type in the text area and can press post to add a comment.
* There should be a placeholder text in the text area saying my comments.
# Tasks
- [x] Create a form where users post comments related posts.
- [x] There should be a button saying post.
- [x] The text area should be resizeable.
- [x] This area must be responsive.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
