### ISSUE TITLE
USER STORY: Users comments list

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#26]
As a **user** I can **view all the comments** so that **I can observe what other think of the post or what others are talking**.
## Acceptance Criteria
* There should be a list of comments under the comments text area.
* The latest comments should be on the top.
* User name, image, and how old the comment is should be mentioned.
* Actual comment should also be there.
# Tasks
- [x] Create a list of comments section under my comment text area.
- [x] Create a method where one comment is on top of another.
- [x] Add Username, image, comment.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
