### ISSUE TITLE
USER STORY: User Profile Information

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#29]
As a **user** I can **see users' profiles** so that **I can see users' posts, their votes and their posts specifically and know more about them**
## Acceptance Criteria
* There should be a user profile image on the left side.
* In the middle there should be a user name.
* Below the user name there should be the total number of posts and total up and down votes.
* Below there should be a user bio.
* Lastly there should be all the posts.
# Tasks
- [x] Create a user profile context containing user profile info.
- [x] User Information to populate the required fields as mentioned.
- [x] Make sure the page is responsive.
- [x] The post should redirect to a single post page on click.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
