### ISSUE TITLE
USER STORY: Popular profiles with highest number of up votes on posts

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#30]
As a **user** I can **see and click profiles on the home page with the highest number of upvotes** so that **I can see what they are posting, see their content and profile data.**
## Acceptance Criteria
* There should be a list of the top popular profiles with the highest number of upvotes.
* The profiles should be clickable.
* On clicking any of these profiles user should be redirected to their profiles.
# Tasks
- [x] Use user profile context and fetch user profile data.
- [x] Based on the data, generate a list of top profiles on the top right of the page but below the nav bar.
- [x] Make sure it's responsive.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
