### ISSUE TITLE
USER STORY: Edit profile image and bio

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#32]
As a **user** I can **edit my profile** so that **to change my profile image and add Bio**
## Acceptance Criteria
* Once the user clicks edit profile the user should be redirected to edit profile page.
* Here user should be able to change the image.
* User should be able to add bio.
* The user can either save the new data or cancel this process.
# Tasks
- [x] Create a method to update the user's profile image.
- [x] Create a method to add/update bio.
- [x] Check the resposiveness.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
