### ISSUE TITLE
USER STORY: Change username

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#33]
As a **user** I can **change the username** so that **I am known by a different name when other users see my profile**
## Acceptance Criteria
* User can click user name and redirect to change username page.
* User can update current username.
* Make sure the user can update the username by clicking the save button
* The process could be canceled by clicking cancel.
* User can't use others' usernames.
# Tasks
- [x] Create a function to update the username.
- [x] Handle if the user tries to update to another username.
- [x] Make sure the page is responsive.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
