### ISSUE TITLE
USER STORY: Trending Page

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#35]
As a **user** I can **view the posts that are trending** so that **I can be up to date with products that are trending in the market.**
## Acceptance Criteria
* User Should be able to click trending on the navbar.
* The trending page should show which products are highly voted on.
* The user should be able to perform a search as well as mentioned in #21 .
* A list of popular profiles should also be available.
# Tasks
- [x] Reuse #21 component on the trending page.
- [x] Apply filter where most upvoted posts are fetched.
- [x] Reuse popular profile component.
- [x] Make sure the page is responsive.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
