### ISSUE TITLE
USER STORY: Sign into web app

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#37]
As a **user** I can **sign in** so that **I can view the latest posts or add new posts**.
## Acceptance Criteria
* The user must provide the username.
* The user must password.
* The username and password should be valid.
* I can wrong data, the user should be given a message to provide correct data.
* User should be redirected to the home page if all data is valid.
# Tasks
- [x] Create a sign-in form.
- [x] Create a method to validate user data.
- [x] The form on the page must be responsive.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
