### ISSUE TITLE
USER STORY: Modal showing rules for creating a post

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#38]
As a **user** I **must know the rules for adding a post** so that **I can add a post without any validation errors or interruptions.**

## Acceptance Criteria
* There should be a show rules text on the form.
* The rules must appear so that show users what the rules are for posting.
* The user is also able to close it.
# Tasks
- [x] Create a modal for rules.
- [x] Modal should close when clicked outside it.
- [x] Modal should close when the user clicks the cross or close button.
- [x] Make sure it's responsive.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
