### ISSUE TITLE
USER STORY: Accepting / Rejecting Friends Request

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#41]
As a **user** I can **accept friend requests** so that **I can keep track of people who can see my private posts**
## Acceptance Criteria
* Friends requests can be seen once the user logs into the application.
* User can add friends if the request is received via the profile page.
* User can reject friend requests in the same manner.
# Tasks
- [ ] Create a component that handles requests.
- [ ] It can also reject friend requests.
- [ ] User should not be able to send a request again once rejected for 3 months.
- [ ] Test responsiveness.
- [ ] Test functionality.
