### ISSUE TITLE
USER STORY: Site navigation using navbar

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#6]
As a **user** I can **switch between nav items** so that **I can navigate to different sections of the website**
## Acceptance Criteria
* The nav items should be separate from one another.
* The navbar should be available on all the pages.
* The navbar bar should be collapsable on smaller screen sizes.
* The navbar items should be clickable and redirect the users to other pages.
# Tasks
- [x] Create the basic structure of the navbar. It should be consistent across all the pages.
- [x] Implement basic routing to different sections of the website and link them to their respective bar links.
- [x] Test the navigation on different pages. Make sure all navbar links work on all screen sizes.
- [x] Add a menu for mobile screens to provide users with a better experience.

**Comment by MBilalQureshi** [comment]
This issue is now closed.
