### ISSUE TITLE
USER STORY: Sign in/sign out

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#7]
As a **user** I can **sign in and out** so that **I can see my data or browse the app and sign out when I no longer want to use the application**
## Acceptance Criteria
* There should be a sign-in button on the navbar so that the user can be redirected to the sign-in page.
* There should be a sign-out button on the navbar so that the user can sign out from the website.
*  Both buttons should be clickable.
* Both buttons should act responsively on different screen sizes.
* The sign-in option should disappear once the user is signed in and the sign-out option should be present. This case is vice versa.
* The signout button on the nav bar must open a modal which should ask if user is sure to sign out.
* The user must given an option to cancel or sign out at the modal.
# Tasks
- [x] Create a sign-in button on the navbar.
- [x] Create a sign-out button on the navbar.
- [x] Both buttons should either send the user to the sign-in page or simply sign the user out.
- [x] Create a sign-out modal and confirm its functionality.
- [x] Test functionality.

**Comment by MBilalQureshi** [comment]
This issue is closed now.
