### ISSUE TITLE
USER STORY: Users Sign Up

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/versus-drf-m5#8]
As a **user** I can **sign up** so that **I can post products and get people to vote on them and also vote on other people's products**
## Acceptance Criteria
* Users should be able to find a clearly labeled "Sign Up" link or button on the navbar.
* On clicking sign up from the navbar user should be redirected to the sign-up page.
* The sign-up process should include username, password and reenter password.
* User should be redirected to the sign-in page once signed up.
* The sign-up process should include validation to ensure users provide valid and unique information.
# Tasks
- [x] Add a prominent and easily accessible "Sign Up" link or button on the navbar.
- [x] Set up a proper link to the sign-up page.
- [x] Username, password, and re-enter password should be fetched once the user clicks to sign up.
- [x] Implement required validation on all the fields entered by the user.
- [x] Return message if fields are empty and the user clicks to sign up.
- [x] Test the sign-up process to ensure its functionality, including validation, data storage, and user feedback.
- [x] Provide valid messages if the password is not strong enough or the username is already taken.

**Comment by MBilalQureshi** [comment]
This issue is closed now.
